### ISSUE TITLE
Multiplier decimal point issue 

### ISSUE THREAD

**Issue by Pocq** [EMCJava/WuWaOpt#1]
I was getting huge numbers, so i tried to mimic your screenshot example stats, seems like this was the problem:

![image](https://github.com/user-attachments/assets/dfdf0267-5c8a-4a53-8079-0793a5bbf1c2)

Also it seems to ignore echo sets? Maybe I'm doing something wrong...

![image](https://github.com/user-attachments/assets/792f568a-df88-4586-93f9-03ef1b734613)

Nice tool. 😊

**Comment by EMCJava** [comment]
Thank you for the feedback!

**Comment by EMCJava** [comment]
Just one more note, it does apply to set effects (two-piece, five-piece), it just so happens that I have some really good Electro sets and Havoc sets. The 30% Spectro bonus from the five-piece set is not worth using (I tried it in game)

**Comment by Pocq** [comment]
Oh, interesting, i also had similar results with mixed sets so it confused me a little. 👍
