### ISSUE TITLE
No EchoName

### ISSUE THREAD

**Issue by ajilidali** [EMCJava/WuWaOpt#10]
After setting the game in simplified chinese and making sure everything is right, i ran the scan tool, which outputted a file with what seem to be correct values except for echo name:
```
- Cost: 4
  Level: 20
  EchoName: ""
  Set: eSunSinkingEclipse
  AttackPercentage: 0.31599998
  Attack: 92
  EchoHash: 6533921490490175972
```
![image](https://github.com/user-attachments/assets/a421c7c0-9218-4bed-bdf5-56891a57e8af)
This is my in-game screen, as you can see I have a 6 by 4 grill 
![untitled](https://github.com/user-attachments/assets/924dfbf6-17cb-446b-8efc-b15ab401fcf4)

**Comment by ajilidali** [comment]
I just realized after some closer reading that it only recognizes echosNames if they are 5 stars.

**Comment by EMCJava** [comment]
Yes, this is expected behavior as all the calculation are based on five star echo, I should have stated that in the readme 🙏🏻
