### ISSUE TITLE
更新后使用扫描器扫描结果有误

### ISSUE THREAD

**Issue by MoonShadow1976** [EMCJava/WuWaOpt#4]
使用15.6英寸笔记本，扫描后发现实际爆伤15%只有5%，很多扫描声骸如此。估计是100%缩放比例导致数字过小，无法准确识别数字1.该系统推荐使用缩放比例为125%。
![image](https://github.com/user-attachments/assets/142c23e8-edab-467b-9f8c-e8b9994190cd)
![image](https://github.com/user-attachments/assets/31ac2cf6-40ea-40bb-933b-f6c9981f431a)

**Comment by EMCJava** [comment]
你好， 可以再尝试一下吗， 我更新了一下样本数据，要是不可以的话我可能还要跟你进一步采样

**Comment by MoonShadow1976** [comment]
> 你好， 可以再尝试一下吗， 我更新了一下样本数据，要是不可以的话我可能还要跟你进一步采样

使用1.2.4版本后没有再出现这个问题
