### ISSUE TITLE
More columns to add teammate/team echo buffs

### ISSUE THREAD

**Issue by Pocq** [EMCJava/WuWaOpt#5]
As of now we have character and weapon stats, when I want to add their buffs I have to add them to either the weapon or the character stats, after revisiting old setups I have a hard time recalling from where those stats came or what assumptions I made. So I think new teammates columns would help. 
Thank you.

**Comment by EMCJava** [comment]
Hay! Thanks for the useful suggestion, the feature has been implemented, please feel free to experience it.
