### ISSUE TITLE
bug with row skip after 9 rows

### ISSUE THREAD

**Issue by YakivGluck** [EMCJava/WuWaOpt#8]
After scanning for 9 rows (54 echoes ) properly, the scanner skips a few rows (from one to three rows, I'm not sure)

**Comment by EMCJava** [comment]
Hey, thank you very much for your feedback! May I ask if this happens consistently? or is it a one-time thing?

**Comment by YakivGluck** [comment]
I just downloaded the newest version (Release_CamellyaLumi.zip) and it still occurs consistently. Most likely it skips 3 rows.

**Comment by EMCJava** [comment]
That's weird, how does the scanner skip those rows? Normally, after scanning the current 3 rows, it scrolls to the next 3 rows. Does the scanner scroll 6 rows at a time after successfully scanning a page? Or are those echoes just missing from the results?(even the scan did click through all these echoes)

**Comment by YakivGluck** [comment]
The way it skips them is also weird. So it works as you sad.
* Skan the upper 3 rows
* Scroll down
* Repeat.
And then after doing that 3 times properly (3 screens with 3 rows with 6 echoes each = 54 echoes) the scanter scrolls down and then starts scanning not the upper 3 rows as usual but the lowest one instead, so this way it skips almost full screen of echoes.

I've also just tried to scan echoes not from the beginning but from the middle. Same thing happened but scanner skipped only half of the screen (so it started scanning the lowest two rows).

As a theory, I assume it happens because after scrolling down echoes on my screen not usually perfectly fit 6 * 4 grid and scanner does not recognize the upper rows. So it's some kind of "observational error" that accumulates and becomes critical after recognizing 3 screens properly.

**Comment by EMCJava** [comment]
Ahh, I think I see the problem now (my fault), so instead of entering the number of echoes you “want” to scan, you should enter the amount of echoes you “have available” to scan, because I did some handling with the last few rows (you can't scroll beyond the last row, so you can't scan from the top).

I've updated the prompt string, let me know if putting in big numbers (or the exact number) solves the problem, thanks for the feedback~
