### ISSUE TITLE
Scanner does not recognize Baby Viridblaze Saurian echo properly

### ISSUE THREAD

**Issue by YakivGluck** [EMCJava/WuWaOpt#9]
While scanning 1-cost Baby Viridblaze Saurian echo
绿熔蜥（稚形）
judging by scanner logs is recognized as 3-cost Viridblaze Saurian
绿熔蜥
For both types of echo it keeps saying in log:
> EchoName: ViridblazeSaurian

And because 1-cost Baby Viridblaze Saurian echo is from different sets Optimizer app do not show it in "Backpack" with scanned echoes.

**Comment by EMCJava** [comment]
Hey, thanks a lot for the feedback! I've tried this several times and it doesn't seem to be happening on my end, but I do remember that this issue did exist in previous versions, can you please confirm that you were running the latest version at the time? (I think it's still version 1.3.1).

**Comment by YakivGluck** [comment]
Yep it was the latest at that time. And I just downloaded the newest version (Release_CamellyaLumi.zip) and the bug is still there.

**Comment by EMCJava** [comment]
I see, would you mind if I gave you a modified scanner just for application screen capturing? That way I can understand the issue better, one screenshot for both the echo would be sufficient(select the echo and run the scanner). You can mask your game ID if you want as it's not needed
[Cap.zip](https://github.com/user-attachments/files/17770005/Cap.zip)

**Comment by YakivGluck** [comment]
Do you mean something like these?
[Viridblaze Saurians.zip](https://github.com/user-attachments/files/17775978/Viridblaze.Saurians.zip)

**Comment by EMCJava** [comment]
It should be fixed now, thanks for the feedback~
